window._CCSettings = {
    platform: "web-desktop",
    groupList: [
        "default",
        "1",
        "2",
        "3",
        "4",
        "yu",
        "qiu",
        "wall",
        "bee",
        "clover",
        "touch",
        "910",
        "911",
        "912",
        "point"
    ],
    collisionMatrix: [
        [
            true
        ],
        [
            false,
            false,
            true,
            null,
            true
        ],
        [
            false,
            true,
            false,
            null,
            true
        ],
        [
            false,
            false,
            false,
            false,
            true
        ],
        [
            false,
            true,
            true,
            true,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            true
        ],
        [
            false,
            false,
            false,
            false,
            false,
            true,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            null,
            true
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            true
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            false
        ]
    ],
    hasResourcesBundle: false,
    hasStartSceneBundle: false,
    remoteBundles: [],
    subpackages: [],
    launchScene: "db://assets/kidshome.fire",
    orientation: "landscape",
    debug: true,
    jsList: [],
    bundleVers: {
        internal: "4210e",
        main: "82b6d"
    }
};
